sonar.projectKey=cyriotosaka_mysticake
sonar.organization=cyriotosaka

sonar.sources=app
sonar.tests=tests

sonar.php.coverage.reportPaths=coverage.xml

# Exclude non-model files from coverage calculation so the % matches local Unit test coverage
sonar.coverage.exclusions=app/Http/**,app/Console/**,app/Providers/**,app/Exceptions/**

sonar.sourceEncoding=UTF-8
